[".local/scripts"]
type = "archive"
url = "https://github.com/DemonInTheCloset/scripts/releases/download/{{ .scriptsver }}/scripts.tar.xz"
exact = true
[".local/share/scripts"]
type = "archive"
url = "https://github.com/DemonInTheCloset/scripts/releases/download/{{ .scriptsver }}/data.tar.xz"
exact = true
[".config/neomutt/powerline"]
type = "git-repo"
url = "https://github.com/sheoak/neomutt-powerline-nerdfonts.git"
refreshPeriod = "168h"
