[".local/scripts"]
type = "archive"
url = "https://github.com/DemonInTheCloset/scripts/releases/download/{{ .scriptsver }}/scripts.tar.xz"
exact = true
[".local/share/scripts"]
type = "archive"
url = "https://github.com/DemonInTheCloset/scripts/releases/download/{{ .scriptsver }}/data.tar.xz"
exact = true
[".config/neomutt/powerline"]
type = "git-repo"
url = "https://github.com/sheoak/neomutt-powerline-nerdfonts.git"
refreshPeriod = "168h"
[".config/nvim"]
type = "git-repo"
url = "https://github.com/DemonInTheCloset/nvim-config.git"
refreshPeriod = "24h"
[".config/awesome"]
type = "git-repo"
url = "https://github.com/DemonInTheCloset/awesome-config.git"
refreshPeriod = "24h"
[".config/kitty/kitty-themes"]
type = "git-repo"
url = "https://github.com/kovidgoyal/kitty-themes.git"
refreshPeriod = "168h"
